-- ============================================================================
-- AWESOME INC. - OLTP CONSTRAINTS (MySQL)
-- ============================================================================
-- Primary Keys, Foreign Keys, and Indexes
-- Author: Neethu Satravada (NS6411)
-- Course: ECE-GY-9941 Advanced Projects
-- ============================================================================

USE awesome_inc_oltp;

-- ============================================================================
-- FOREIGN KEY CONSTRAINTS
-- ============================================================================

-- FK 1: NS_SUB_CATEGORY → NS_CATEGORY
ALTER TABLE NS_SUB_CATEGORY
ADD CONSTRAINT NS_SUB_CATEGORY_CATEGORY_FK
FOREIGN KEY (CATEGORY_ROW_ID) 
REFERENCES NS_CATEGORY(ROW_ID);

-- FK 2: NS_PRODUCT → NS_SUB_CATEGORY
ALTER TABLE NS_PRODUCT
ADD CONSTRAINT NS_PRODUCT_SUB_CATEGORY_FK
FOREIGN KEY (SUB_CATEGORY_ROW_ID) 
REFERENCES NS_SUB_CATEGORY(ROW_ID);

-- FK 3: NS_CUSTOMER → NS_SEGMENT
ALTER TABLE NS_CUSTOMER
ADD CONSTRAINT NS_CUSTOMER_SEGMENT_FK
FOREIGN KEY (SEGMENT_ROW_ID) 
REFERENCES NS_SEGMENT(ROW_ID);

-- FK 4: NS_ORDER → NS_CUSTOMER
ALTER TABLE NS_ORDER
ADD CONSTRAINT NS_ORDER_CUSTOMER_FK
FOREIGN KEY (CUSTOMER_ROW_ID) 
REFERENCES NS_CUSTOMER(ROW_ID);

-- FK 5: NS_ORDER_DETAIL → NS_ORDER
ALTER TABLE NS_ORDER_DETAIL
ADD CONSTRAINT NS_ORDER_DETAIL_ORDER_FK
FOREIGN KEY (ORDER_ROW_ID) 
REFERENCES NS_ORDER(ROW_ID);

-- FK 6: NS_ORDER_DETAIL → NS_PRODUCT
ALTER TABLE NS_ORDER_DETAIL
ADD CONSTRAINT NS_ORDER_DETAIL_PRODUCT_FK
FOREIGN KEY (PRODUCT_ROW_ID) 
REFERENCES NS_PRODUCT(ROW_ID);

-- FK 7: NS_RETURN → NS_ORDER
ALTER TABLE NS_RETURN
ADD CONSTRAINT NS_RETURN_ORDER_FK
FOREIGN KEY (ORDER_ROW_ID) 
REFERENCES NS_ORDER(ROW_ID);

-- FK 8: NS_RETURN_DETAIL → NS_RETURN
ALTER TABLE NS_RETURN_DETAIL
ADD CONSTRAINT NS_RETURN_DETAIL_RETURN_FK
FOREIGN KEY (RETURN_ROW_ID) 
REFERENCES NS_RETURN(ROW_ID);

-- FK 9: NS_RETURN_DETAIL → NS_ORDER_DETAIL
ALTER TABLE NS_RETURN_DETAIL
ADD CONSTRAINT NS_RETURN_DETAIL_ORDER_DETAIL_FK
FOREIGN KEY (ORDER_DETAIL_ROW_ID) 
REFERENCES NS_ORDER_DETAIL(ROW_ID);

-- ============================================================================
-- INDEXES FOR PERFORMANCE
-- ============================================================================

CREATE INDEX IDX_CUSTOMER_SEGMENT ON NS_CUSTOMER(SEGMENT_ROW_ID);
CREATE INDEX IDX_CUSTOMER_COUNTRY ON NS_CUSTOMER(COUNTRY);
CREATE INDEX IDX_ORDER_CUSTOMER ON NS_ORDER(CUSTOMER_ROW_ID);
CREATE INDEX IDX_ORDER_DATE ON NS_ORDER(ORDER_DATE);
CREATE INDEX IDX_ORDER_DETAIL_ORDER ON NS_ORDER_DETAIL(ORDER_ROW_ID);
CREATE INDEX IDX_ORDER_DETAIL_PRODUCT ON NS_ORDER_DETAIL(PRODUCT_ROW_ID);
CREATE INDEX IDX_PRODUCT_SUBCATEGORY ON NS_PRODUCT(SUB_CATEGORY_ROW_ID);
CREATE INDEX IDX_SUBCATEGORY_CATEGORY ON NS_SUB_CATEGORY(CATEGORY_ROW_ID);
CREATE INDEX IDX_RETURN_ORDER ON NS_RETURN(ORDER_ROW_ID);

-- ============================================================================
-- CONSTRAINT SUMMARY
-- ============================================================================
/*
RELATIONSHIPS:
──────────────────────────────────────────────────────────────────
| Child Table       | Column             | Parent Table    | Column  |
──────────────────────────────────────────────────────────────────
| NS_SUB_CATEGORY   | CATEGORY_ROW_ID    | NS_CATEGORY     | ROW_ID  |
| NS_PRODUCT        | SUB_CATEGORY_ROW_ID| NS_SUB_CATEGORY | ROW_ID  |
| NS_CUSTOMER       | SEGMENT_ROW_ID     | NS_SEGMENT      | ROW_ID  |
| NS_ORDER          | CUSTOMER_ROW_ID    | NS_CUSTOMER     | ROW_ID  |
| NS_ORDER_DETAIL   | ORDER_ROW_ID       | NS_ORDER        | ROW_ID  |
| NS_ORDER_DETAIL   | PRODUCT_ROW_ID     | NS_PRODUCT      | ROW_ID  |
| NS_RETURN         | ORDER_ROW_ID       | NS_ORDER        | ROW_ID  |
| NS_RETURN_DETAIL  | RETURN_ROW_ID      | NS_RETURN       | ROW_ID  |
| NS_RETURN_DETAIL  | ORDER_DETAIL_ROW_ID| NS_ORDER_DETAIL | ROW_ID  |
──────────────────────────────────────────────────────────────────
*/

-- ============================================================================
-- END OF CONSTRAINTS
-- ============================================================================
